update_unicode_latex <- function() {
  url <- "https://milde.users.sourceforge.net/LUCR/Math/data/unimathsymbols.txt"

  # FIXME: If we use `quote = ""`, there will be 2757 rows instead of 1740 rows
  tbl <- utils::read.table(
    url,
    header = FALSE,
    sep = "^",
    comment.char = "#",
    stringsAsFactors = FALSE,
    fill = TRUE
  )

  tbl <- tbl[, c(1, 3)]
  tbl <- cbind(tbl, NA)
  names(tbl) <- c("unicode", "latex", "int")

  # FIXME: Apply a few completely ad hoc filters to get
  # data frame identical to the version saved in .rda
  tbl <- tbl[tbl$latex != "", , drop = FALSE]
  tbl <- tbl[grepl("^\\\\", tbl$latex), , drop = FALSE]
  tbl$int <- strtoi(tbl$unicode, base = 16)
  tbl <- tbl[tbl$int >= 177L, , drop = FALSE]
  tbl <- tbl[!(tbl$latex %in% c(
    "\\Micro", "\\times", "\\eth", "\\div", "\\bullet",
    "\\vec", "\\eqcolon", "\\square", "\\blacksquare"
  )), , drop = FALSE]
  row.names(tbl) <- NULL

  rows <- lapply(
    seq_len(nrow(tbl)),
    function(i) {
      sprintf(
        '  c(unicode = "%s", latex = "%s", int = %d)',
        tbl$unicode[i],
        gsub("\\", "\\\\", tbl$latex[i], fixed = TRUE),
        tbl$int[i]
      )
    }
  )

  writeLines(c(
    "# Generated by R/utils.R: do not edit by hand",
    "# Please run update_unicode_latex() to regenerate this file",
    "",
    "unicode_latex <- data.frame(rbind(",
    paste(rows, collapse = ",\n"),
    "), stringsAsFactors = FALSE)",
    "",
    "unicode_latex$int <- as.integer(unicode_latex$int)"
  ), con = "R/unicode_latex.R")
}
